GET http://127.0.0.1:8787/

###

POST  http://127.0.0.1:8787/register
Content-Type: 'application/json'

{
    "username":"Aradhya Tiwari",
    "email":"aradhya.prad@gmail.com", 
    "password":"132grthny64ujmhgrfe"
}
###
POST  http://127.0.0.1:8787/register
Content-Type: 'application/json'

{
    "username":"Divyansh Tiwari",
    "email":"divyansh.prad@gmail.com", 
    "password":"abcd123"
}
###
POST  http://127.0.0.1:8787/login
Content-Type: 'application/json'

{
    "username":"Aradhya Tiwari",   
    "password":"132grthny64ujmhgrfe"
}

###
POST  http://127.0.0.1:8787/login
Content-Type: 'application/json'

{
    "username":"Divyansh Tiwari",   
    "password":"abcd123 "
}

###
