GET http://127.0.0.1:8787/

###

POST  http://127.0.0.1:8787/register
Content-Type: 'application/json'

{
    "name":"Divyansh Tiwari",
    "class":"ET A" 
    
}

###
POST https://api.chatbot.com/v2/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjM3MDdlOGRjNDgyYjAwMDcwNGQ4ZjUiLCJvcmciOiI2NjM3MDc4MTExYTc5ODAwMDdmOTBhNGIiLCJzY29wZSI6ImNoYXQiLCJtZXRhIjp7InNvdXJjZSI6ImFwcCIsInN0b3J5SWQiOiI2NjM3MDdkNDA5ZGE2NDAwMDczMWQwMzgiLCJzaWQiOiIyMjJkY2VjMy04YWFjLTRmMmMtYjU1OS0wZjU3N2ViNDEwNzkifSwiaWF0IjoxNzE0ODgyNTM2LCJleHAiOjE3MTQ5MTEzMzYsImF1ZCI6ImFwaS5jaGF0Ym90LmNvbSIsImlzcyI6ImFwaS5jaGF0Ym90LmNvbSIsImp0aSI6IjE3MGI1YmIyLTg0NzAtNGI3Mi1hN2E5LWVkOTA0NTJhYTRhMSJ9.36nZWuiczLS2Lvcde4ba7pvB4PN99iVe41w5rSFw2T0
Origin:https://app.chatbot.com
Content-Type: application/json

{"inputType":"MESSAGE","inputValue":"how are you"}